### ISSUE TITLE
There is two columns of Title in the content Menu

### ISSUE THREAD

**Issue by aryamanpuri** [plone/volto#1107]
**Describe the Bug**
Selecting the `Title` from all the options in the dropdown menu.
There are two Title columns in the content Menu.

**Expected Behaviour**
There should be one Title column in the Content menu.

![Screenshot from 2020-01-14 16-39-04](https://user-images.githubusercontent.com/43513114/72339667-b7ad6f80-36ec-11ea-91dc-42ac259ee0cc.png)

@tisto 
@sneridagh

**Comment by jackahl** [comment]
@aryamanpuri with dropdown you mean the one for sorting the contents, right?

**Comment by aryamanpuri** [comment]
The option above the Actions in the menu

**Comment by jackahl** [comment]
Ah ok. Didn't even know that existed :D

**Comment by jackahl** [comment]
@aryamanpuri I looked a bit into it. The best solution IMO would be to remove the title option from the dropdown because the first title column is hardcoded. I already wrote a try here: https://github.com/plone/volto/pull/1108
Maybe you can also take a look at it. Maybe you find a more elegant solution. Lodash might offer something for that https://lodash.com/docs/4.17.15#map, but I don't have the time to look into it further.
