### ISSUE TITLE
Error after create-volto-app

### ISSUE THREAD

**Issue by LeuAlmeida** [plone/volto#1126]
I runned **create-volto-app myapp** and bootstraped the backend runnning `$ docker run -it --rm --name=plone -p 8080:8080 -e SITE=Plone -e ADDONS="kitconcept.voltodemo" -e ZCML="kitconcept.voltodemo.cors" plone`. 

My output on `$ yarn start` is:
```shell
yarn run v1.19.1
$ razzle start
 WAIT  Compiling...


✔ Client
  Compiled successfully in 19.98s

✔ Server
  Compiled successfully in 2.08s

ℹ ｢wds｣: Project is running at http://localhost:3001/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /home/leu/Desktop/intranet
ℹ ｢wds｣: 404s will fallback to /index.html
✅  Server-side HMR Enabled!
🚀 started
```

On **localhost:3001** i got `Cannot GET /`, but at localhost:3000 is all ok. But when i try to register an user, the right arrow try to load but nothing happen.

Somebody had this problem? How can i solve this?

Backend docker output:
```shell
Starting server in PID 1.
Serving on http://0.0.0.0:8080
```

**Comment by sneridagh** [comment]
Hi @LeuAlmeida 
Have you take a look at: https://docs.voltocms.com/ ?
The documentation is still incomplete, but will give you an insight of how Volto works. As it works with Plone, the default is not to allow register users, try to do so from the control panel. Also, registering a user works the same way that in Plone, so a mail goes out with a confirmation URL. Probably as the mail serveer wasn't configured, the request failed. It's still due to catch the failed requests and show the problem via the UI, but you can take a look at the console or network tab and see the problem.

**Comment by sneridagh** [comment]
Also `create-volto-app` is using the 3.x.x version, you can try the last alpha using `npx @plone/create-volto-app@alpha my-volto-app.

**Comment by LeuAlmeida** [comment]
Thanks for your help @sneridagh . Tomorrow i will try again using npx
