### ISSUE TITLE
Rearrange API and acceptance tests folders in the repo

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#119]
@datakurre Great work with the acceptance tests! The Jupyter notebook is really impressive.

I was thinking these last days into set into production a plone-react demo site, so I created:
https://hub.docker.com/r/kitconcept/plone.restapi/

I've been taking a look at how now the `api/` repo folder looks like and I think that is a bit confusing in his current shape. I would arrange it to separate the acceptance tests part and the buildout/pip/docker build for quick test the API and development purposes, and document how to use them both. It's true that we could use the docker image with the current state for that, but I think that the port change and the robot server approach would confuse people, specially newcomers.

@tisto @datakurre What do you think?

**Comment by ajayns** [comment]
By using buildout/pip/docker build do you mean using what @datakurre mentioned? The docker image: https://hub.docker.com/r/ericof/plone/

@sneridagh If that's what we're talking about I'd like to see it implemented, so that I use it as reference while working with the same for Gatsby!

**Comment by datakurre** [comment]
Hi,

./api/docker uses robot-server instead of normal Plone instance (like in
ericof/docker-plone) to ensure that the environment is always equal to the
environment in CI. (Also, I did not extend from erico/plone, because I
was not sure if you'd like to officially depend on it.)

Port and path can be fixed in Dockerfile with

ENV ZSERVER_PORT=8080
RUN sed -i "s|'plone'|'Plone'|" lib/python2.7/site-packages/plone/app/testing/interfaces.py

(There is currently no way to monkeypatch PLONE_SITE_ID module variable
before plone site fixture has already been created.)

Of course, you could replace robot-server based Dockerfile simply with

FROM ericof/plone:5.1.0
RUN bin/pip install plone.restapi

but then you'd need to manually create Plone site to be able to develop
tests against it. Yet, I agree that it might be less effort than
explaining to anyone what in the world that "robot-server" :)

Cheers,
Asko

Quoting Víctor Fernández de Alba (2018-03-18 23:43:38)

**Comment by sneridagh** [comment]
@datakurre I'm more in the mood of leave the acceptance test ones in its current shape, then provide the docker instance with a standard Plone site with Plone as id on 8080 and restapi already installed and keep both separate, as they might concern to two different types of audiences.

I will make a proposal and PR it.
