### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by ksuess** [plone/volto#1317]
To be discussed: naming convention for new var names

A subchapter of
https://github.com/plone/volto/tree/master/docs/source/developer-guidelines to "Naming convention" would come in handy.

**Comment by ksuess** [comment]
My intention for this issue is making/keeping the onboarding for js developers to Volto Plone community easy. Or as Piero wrote 
_To add more on that, I think that if we want to make it easier to onboard js devs in the Plone world with volto, keeping it as close to the community standards should be the goal._

See comment of @tisto voting for snake_case https://github.com/plone/plone.restapi/pull/888#discussion_r399798246

See comment of @pnicolli voting for camelCase https://github.com/plone/plone.restapi/pull/888#discussion_r400684908

**Comment by tisto** [comment]
Neither JavaScript nor React have a naming convention or even recommendation. create-react-app also does not have an official recommendation or eslint check. Though both react and create-react-app seems to use camelCase for variable names internally.

FYI: I did not vote for snake_case in Volto. We decided to use snake_case for plone.restapi attributes because it is Python and because of historic reasons. We could easily choose camelCase as a convention in Volto.

Personally I have a preference for snake_case because I find it more readable than camelCase. Though, camelCase seems to be the dominant convention in the JS world.

I created a PR that checks the eslint camelCase rule. We have 300 violations in Volto core currently:

https://github.com/plone/volto/pull/1319

@sneridagh @robgietema wanna weight in?
