### ISSUE TITLE
Publishing Date and Expiration Date are pre-set with current date/time

### ISSUE THREAD

**Issue by tisto** [plone/volto#1422]
Volto master

1) as admin
2) go to portal root and create a new page
-> Publishing Date and Expiration Date are pre-defined in the right sidebar
-> should: Publishing Date and Expiration Date should not be set

![Add Document (1)](https://user-images.githubusercontent.com/632105/80228843-dd350800-864f-11ea-9dfd-d2fdc2ddaf17.png)

**Comment by tisto** [comment]
@nzambello this is new. any idea what could cause this?

**Comment by nzambello** [comment]
The default value for the widget, if a date is not set from Plone, is the current date.
Now it's marked with the grey color to make that different from a set one.
This behavior is fine for event dates and when editing content publish/expire dates, but probably not enough for new content ones.

Instead of making it grey I could make it invisible, but I have to keep a date set for the date picker.

**Comment by nzambello** [comment]
What do you think @tisto @sneridagh ?

**Comment by tisto** [comment]
@nzambello making it invisible is fine with me. This is a pure UX issue, not a functional bug.

**Comment by sneridagh** [comment]
I would just "disable" it via CSS, so it remains not visible until the user clicks and makes the widget show. Is that easy to do?

**Comment by sneridagh** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/486927/83253972-37287080-a1ae-11ea-80d1-76880a855381.png">

**Comment by tisto** [comment]
@iFlameing could you rebase your Cypress tests PR with master and see if the test passes now?
