### ISSUE TITLE
Translations in customizations 

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1846]
If I add a customization for a component, for example for Footer.jsx component in customizations/components/Footer/Footer.jsx
and i add some new strings that i want to translate, when running yarn i18n new strings ar not added to .po files, and i cannot translate theme

**Comment by giuliaghisini** [comment]
i think the problem is here
https://github.com/plone/volto/blob/170f2bb7cbf44cfac18878920d9bd1e55e30ba64/src/i18n.js#L42

**Comment by ionlizarazu** [comment]
this problem persists, now at: https://github.com/plone/volto/blob/ac0602fdb3fb2cfd0c698c58a99760e74a75acf4/packages/scripts/i18n.js#L34

Why don't we want to extract the messages from customizations?

**Comment by tiberiuichim** [comment]
@sneridagh maybe knows

**Comment by sneridagh** [comment]
That's on purpose I'm afraid. The customizations are excluded feom the local i18n recollection. The reason is that if this was not done, all the translations donenin that customized component would have been resetted instead.

If you need a new translation in a customization the eay to go is to define it somewhere else (we always do that in config.js, although any ither place would do).

**Comment by tiberiuichim** [comment]
@sneridagh so,  what you're saying is that if you want to do template customizations, you should do it in an addon, right? ;-)

**Comment by sneridagh** [comment]
@tiberiuichim I think the add-on i18n config inherits the same limitations :) , so the customizations in there will also be ignored, forcing you to extract any new translation present in customisations out of the original (in this case, customised) component.

**Comment by ionlizarazu** [comment]
@sneridagh thats our situation. We have customized components in addons and the new texts are ignored to translations

**Comment by sneridagh** [comment]
The overall i18n story and how react-intl works and thus, the limitations that we faced because the customizations aliases and then the add-ons story are not straight forward to explain, I can do that extensively in next Volto Team meeting. Maybe we could find another solution that still works, but I couldn't find one better.

**Comment by sneridagh** [comment]
@ionlizarazu the solution is to use a module out of the customizations folder for defining them. eg. `index.js` for simplicity (or you could use any other). Then, address to it from the customisation.

**Comment by sneridagh** [comment]
for further simplicity, do not address them, use the `id` and `defaultMessage` from the `formatMessage` call.

**Comment by sneridagh** [comment]
Oh and remember that defining them is a two step pass! So might require two runs of the i18n script! One for getting them from the messages and make the po aware of it, other for writing down the actual translation into the json files.

**Comment by jensens** [comment]
This should go in the docs.

**Comment by stevepiercy** [comment]
This file needs to be updated accordingly: https://6.docs.plone.org/volto/development/i18n.html

I don't understand what @sneridagh wrote, but perhaps some of you do, and I would be grateful for any help with improving the i18n docs to include how to accomplish this task.
