### ISSUE TITLE
Problems with proxy, authenticated users and rdirections

### ISSUE THREAD

**Issue by cekk** [plone/volto#1883]
Making some tests locally for #1095 i've found a possible problem with the development proxy.

What i'm testing: when accessing a renamed document (aaa -> bbb) with its old path (/aaa), i should see it.

If i stay with standard config (Plone site running on 8080), everything works fine.

If i change the api endpoint (for example changing the port to 8081) and i add a **RAZZLE_API_PATH** env var with the custom addres (without touching **devProxyToApiPath**), i can access the website and working on it.
If i try to access to /aaa as anonymous user, i can correctly see the page.
If i log-in, that page generates and error [here](https://github.com/plone/volto/blob/master/src/helpers/Api/Api.js#L70) basically because when logged-in, i have the Auth token and the browser send some preflight requests (OPTIONS) to the server before the actual requestes, but these fails because of CORS: Redirect is not allowed for a preflight request.

This could be one of the reasons because you added the development proxy, i suppose.
The problem is that if i update it with the actual api url (RAZZLE_API_PATH), i get the same error.

Any ideas @sneridagh ?

**Comment by tiberiuichim** [comment]
I think it's a bug. devProxyToApiPath should also read from RAZZLE_API_PATH

**Comment by sneridagh** [comment]
OK, after refreshing myself, (crap I'm super rusty, working hard on it) ;P I figured it out.

So, the proxy is only meant to be used in development (at least how I conceived it). You already know it but to refresh it and have it written it down:

I pushed the proxy hard to improve the approach-ability to Volto and not having to setup the CORS in Plone to use it, and while doing this, not introduce any substantial change to the Volto innards and configuration options. The outcome is a somehow not super intuitive way of configure it, and having this separated variables. I'm open to suggestions how we can improve this!

The idea is then, that Volto (in development) will always use the proxy path and port (which is fixed), and if you have the dev server in another port/place, then use that by modifying `devProxyToApiPath` (in the config, I didn't expose it as a RAZZLE variable on purpose, since it's not meant to be used in production). By doing this, we left RAZZLE_API_PATH for production only (if you want to use the proxy during development). 

If you want to disable the proxy (and use RAZZLE_API_PATH), you can do so by setting `devProxyToApiPath` to an empty string.

So with this,
```
devProxyToApiPath: 'http://localhost:8081/Plone'
```
and not setting RAZZLE_API_PATH it works well.

Only as side note, with some tweaks in the proxy config (mainly due to http-https proxy issues) you can point the proxy to any external server.

**Comment by cekk** [comment]
Thanks for explaining that..it's super clear now.

Have you tried the redirect with custom proxy address and logged user?
