### ISSUE TITLE
Internal URLs and custom routes

### ISSUE THREAD

**Issue by nzambello** [plone/volto#2411]
In some projects, clients need to publish other stuff under a certain route.
Some have several.
So, if I'm publishing a Volto site as https://plone.org I may have https://plone.org/abc as a reserved route publishing another application.

In Volto, /abc is recognized as an internal URL and Volto will load /abc as Plone content when navigating client side (so it will break itself).

@plone/volto-team Do you have anything in mind to avoid that?

**Comment by sneridagh** [comment]
Volto recognize it as its own if you follow a Router link, but not if you are following a notmal link.

The rest is Nginx config, so /abc points outside, right?Maybe I'm missing something...

**Comment by nzambello** [comment]
Using UniversalLink that is recognized as internal
We have those in listings and they are handled as normal links inside volto

**Comment by sneridagh** [comment]
Oh I see... meh! use a blacklist?

**Comment by tiberiuichim** [comment]
I think this should be handled by the router. We actually have a similar use case as well, not sure how @avoinea solved it.

Maybe hook into the router's actions? We use https://github.com/supasate/connected-react-router

**Comment by avoinea** [comment]
In my case volto is at `/abc` and everything else is Plone Classic thus I force all the Navigation links to reload the page https://github.com/eea/volto-ims-theme/blob/master/src/customizations/components/theme/Navigation/Navigation.jsx#L206, then Nginx/HAProxy steps in and redirect the traffic.

I know, a dirty hack, that's why I'm open for a more elegant solution.
