### ISSUE TITLE
Incomplete upgrade guide on plone/scripts

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2715]
The wording in the upgrade guide makes it seem that only the addons need plone/scripts as dependency. But it seems that the projects need it too.

**Comment by ichim-david** [comment]
I could be wrong but I think that the reason for which there was no need for dependency on plone/scripts is because
if you upgrade to Volto 14, Volto itself depends on plone/scripts
https://github.com/plone/volto/blob/master/package.json#L250
in care the line will change right now it references the following dependency:
plone/scripts: '1.0.3'

@sneridagh am I right or wrong on this assumption?
