### ISSUE TITLE
seamless mode: combining RAZZLE_API_PATH with production build, Volto startup echos wrong listening port

### ISSUE THREAD

**Issue by fredvd** [plone/volto#2972]
Volto 14.2 clean scaffold, Plone 6.0 website as backend.

I'm testing seamless mode and trying to run the backend on a non default port (not 8080 but in this case 9261) and use RAZZLE_API_PATH.

When I do a production build and then start the production build, this is the terminal output:
```
 RAZZLE_API_PATH=http://localhost:9261/plone/ yarn start:prod
yarn run v1.22.17
$ NODE_ENV=production node build/server.js
API server (API_PATH) is set to: http://localhost:9261/plone/
🎭 Volto started at http://localhost:9261 🚀
```

Notice the last line, Volto isn't started on port 9261, but still listens on port 3000 . 

The development startup does list the correct port:

```
RAZZLE_API_PATH=http://localhost:9261/plone/ yarn start
yarn run v1.22.17
$ razzle start
 WAIT  Compiling...
✔ Client
  Compiled successfully in 530.06ms
✔ Server
  Compiled successfully in 2.28s
✅  Server-side HMR Enabled!
API server (API_PATH) is set to: http://localhost:9261/plone/
Using internal proxy: http://localhost:3000 -> http://localhost:9261/plone/

🎭 Volto started at http://localhost:3000 🚀
```

**Comment by sneridagh** [comment]
I've taken a look at this, and the reasoning behind is:

https://github.com/plone/volto/blob/7a70d9b0ace2ef697578a3dccd0088596653c2ce/src/config/index.js#L50-L54

> Sensible defaults for publicURL
> if RAZZLE_PUBLIC_URL is present, use it
> if in DEV, use the host/port combination by default
> if in PROD, assume it's RAZZLE_API_PATH server name (no /api or alikes) or fallback
> to DEV settings if RAZZLE_API_PATH is not present

This is because it's assuming that in production you are going to use recommended deployment, so you don't have to deal with CORS (believe me, you don't want to deal with it, even if you really want it :) ) 

But I agree, that might be confusing, also uninformative, let me make a slight change for now.
