### ISSUE TITLE
Regression in `contents` view because of #3245

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#3273]
This should be the outcome of the folder contents:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/486927/165500009-5407efcd-c20c-4262-9b05-9002c403e701.png">

And instead, now we get this:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/486927/165500084-f0e7806a-aea1-4b1c-b213-9150cba3ee44.png">

**Comment by giuliaghisini** [comment]
we know.. he had to give a min-height to view the actions menu when open... we know is not the best solution, maybe a popup (and i think there's something on working...) is a best solution, but for now this fixes usability when you have only one or two items in folder contents

**Comment by sneridagh** [comment]
Crap @giuliaghisini @SaraBianchi I mixed things, and I thought that your PR was this one:

https://github.com/plone/volto/pull/3158

I think this is the way to go...

**Comment by dobri1408** [comment]
Hey, I think that a way to solve this issue is to automatically increase the height of the folder contents when the actions menu is open and decrease it when the actions menu is closed. What do you think?


![Screenshot 2022-05-02 at 19-39-17 Contents](https://user-images.githubusercontent.com/50819975/166289094-5a9dcb37-7724-425c-9f2f-5861ab43c03d.png)



![Screenshot 2222 2022-05-02 19-40-24](https://user-images.githubusercontent.com/50819975/166289121-2ab7b125-7fae-4cfc-860f-b32d0d704c97.png)

**Comment by SaraBianchi** [comment]
@dobri1408 @sneridagh 
perhaps the best solution is @danielamormocea 's, the dropdown menu comes out of the table and doesn't change its height.

<img width="1311" alt="Schermata 2022-05-05 alle 10 06 40" src="https://user-images.githubusercontent.com/43245702/166885961-a52464c1-32c1-4c9e-ae5f-7cb6648fbd41.png">

**Comment by sneridagh** [comment]
I'll go with https://github.com/plone/volto/pull/3158... although some concerns should be fixed in there. 
What do y'all think?

**Comment by giuliaghisini** [comment]
> I'll go with #3158... although some concerns should be fixed in there. What do y'all think?

For me it's ok!

**Comment by sneridagh** [comment]
Fixed and merged.
