### ISSUE TITLE
Slate Table block doesn't match /table as block input shortcut

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3960]
![image](https://user-images.githubusercontent.com/141568/203514832-782935ed-05f7-4024-b497-9c4cf75d93f9.png)

Volto 16.0.0

**Comment by iRohitSingh** [comment]
@tiberiuichim because id of table block is slate "slateTable" and in code we are matching first letter. That`s why we are unable to see table block. 
What should be my next step?

<img width="518" alt="Screenshot 1944-09-02 at 21 14 02" src="https://user-images.githubusercontent.com/61353484/203588713-b354f45f-9f2b-4572-97a3-17a7f5c027c6.png">

**Comment by tiberiuichim** [comment]
@iRohitSingh one quick solution would be that the quicksearch should do a match over the entire text (I'd go as far as block title, but that's discussable. @sneridagh thoughts on this?)

**Comment by davisagli** [comment]
@tiberiuichim @iRohitSingh I'm not sure whether we should look for a match that is not at the start of the block id. But I do think we should also match on the block title (case insensitively). The user is more likely to know the title than the internal id, which might not even be in their language.
