### ISSUE TITLE
Block types menu does not show some blocks when filtering by first letter

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#4173]
**Describe the bug**

The block types menu does not show some blocks, and shows some unexpected blocks, when filtering by the first letter.

**To Reproduce**

1. Go to https://6.demo.plone.org/edit
2. Insert a new block.
3. Type `/t` to bring up the block types menu.
4. Table does not appear in the filtered results, but three other block types that start with "T" appear.

I tested additional filters for blocks that are in the full list and found more surprising results.

- `g`: Grid does not appear.
- `s`: Returns Search and System as expected, but also Table and Text.
- `t`: Returns only Table of Contents, Teaser, and Teaser Grid, but not Tablet and Text.

**Expected behavior**

The appropriate blocks should appear when its first letter is typed.

**Screenshots**

![Screen Shot 2022-12-22 at 11 23 48 PM](https://user-images.githubusercontent.com/102112/209291226-53932d57-d266-471a-b2c3-20fe5320f21a.png)

**Comment by arpitghura** [comment]
Hey @stevepiercy I am not able to regenerate the error. On my editor, it is perfectly working.

![image](https://user-images.githubusercontent.com/41796013/209341842-f34b43ca-0abd-4412-8903-a17adf2e3463.png)

**Comment by stevepiercy** [comment]
Thanks for the data point. Did you try on the demo site, or local installation?

**Comment by arpitghura** [comment]
Yes, I have tried on demo site online.

**Comment by stevepiercy** [comment]
@arpitghura which browser and OS combinations?

I noticed `Text` does not appear for you.

I do not see `Table` or `Text` when I type `/t` on macOS in the following browsers:

- Chrome Version 108.0.5359.124 (Official Build) (x86_64).
- Firefox 108.0.1 (64-bit)
- Safari Version 15.6.1 (15613.3.9.1.16, 15613)

**Comment by davisagli** [comment]
I think I understand why some of these are happening:
- The text block is intentionally omitted from the choices, because the block is already a text block.
- `g` does not find the Grid, because it's actually called the Teaser Grid (teaserGrid internally), and the code is only matching at the beginning of the id and title: https://github.com/plone/volto/blob/master/packages/volto-slate/src/blocks/Text/SlashMenu.jsx#L121-L22 (I think this is a bug; we intended to change it to match any substring in #4116).
- `s` includes the Table block because it is called slateTable internally.

I don't yet understand:
- why `t` does not find the Table block (it works locally)
- why `s` includes the Text block (it should still be filtered out by https://github.com/plone/volto/blob/master/packages/volto-slate/src/blocks/Text/SlashMenu.jsx#L121-L22)
