### ISSUE TITLE
Add end-to-end testing

### ISSUE THREAD

**Issue by robgietema** [plone/volto#5]
Add e2e testing setup using `protractor` and create tests for basic flows.

**Comment by tisto** [comment]
@robgietema for our projects we decided to use Robot Framework for Angular 2 because it allows real end-to-end tests (integrated with the zope testrunner) and a sane syntax (personally I really dislike the jasmine syntax). No matter what your decision is, I would be able to provide some high-level BDD scenarios for the basic Plone functionality that we could use as a starting point for acceptance tests.

**Comment by robgietema** [comment]
@tisto that would be really nice, Robot Framework is fine by me.

**Comment by datakurre** [comment]
Implemented at https://github.com/plone/plone-react/pull/102

**Comment by sneridagh** [comment]
Recently someone demo'd to me Cypress... very impressive, pity that it lacks the BDD approach and only works (for now) in Chrome.

**Comment by datakurre** [comment]
It seems that for every year there has been some fancy new tech for e2e web UI testing. The last Robot Framework conference had fun presentation about a tester who had been using Robot always 10 years. About everything else had changed, but Robot as a testing tool had lasted https://youtu.be/0CnTjUVwIKc?t=1491 :-)

**Comment by tisto** [comment]
We have end-to-end testing with cypress and robot-server now. Best of both worlds. :)
