### ISSUE TITLE
Image component: aspect-ratio is overridden thus broken, width + height calculated incorrectly

### ISSUE THREAD

**Issue by reebalazs** [plone/volto#5096]
**Describe the bug**
The image component overwrites the aspect-ratio specified from css. It also generates width and height properties from the actual image size, which is incorrect.

**To Reproduce**

Add an `aspect-ratio` to your image via css class, 

```jsx
<Image item={item} className="myClass" />
```

From css:

```css
.myClass {
  aspect-ratio: 2;
}
```

The result is that the accept ratio of 2 is ignored, and the image is displayed with its original aspect ratio.

**Expected behavior**

The image is displayed with the aspect ratio specified in the css.

**Software**

- Browser: any
- Volto Version: `17.0.0-alpha.24`

**Additional context**

1. Problem with generating the width and height

The Image component generates the width and the height from the image size, if not specified explicitly. This is wrong. The point of the width, height attributes is to avoid layout shift by hinting the browser in the html about the *rendered* image size, not the *actual* image size.

Sure, if I specify width and height then it will use these values. However putting the real image size to this attributes does not help layout shift, as the rendered image size will most certainly not be the same as the original uploaded image size.

Possible actions:

a. Do not generate the width and height, if not specified. Leave it to the developer. There is no way it can be predicted on SSR, what the rendered width and height will be, only the developer can know.

b. If you think width and height are really mandatory, (imo not, as it's just a hint to avoid layout shift), then make them mandatory. 

2. aspect-ratio is overritten

In connection with problem 1, the aspect-ratio specified from css is overridden and thus the image is displayed with the wrong aspect ratio. 

  - If I specify width+height, it will override the aspect ratio set on the css, by using the width and height I specified
  
  - If I do not set width+height, it will calculate it from the image size, and again it will override the aspect ratio

In both cases it won't be the correct aspect ratio. The only way it will be correct, if I specify width and height. However this makes the aspect-ratio css attribute lose its purpose.

Possible actions:

a. do not generate the aspect-ratio, let's use css as intended, and let's leave it to the developer to use it the way they want.

b. Only generate the aspect-ratio, in case it's not already specified from css (it's possible to check this in client runtime only, no SSR) but again, kind of pointless if you also consider point 1.

**Comment by davisagli** [comment]
@pnicolli Thoughts?

**Comment by pnicolli** [comment]
I had a similar discussion with Victor a couple weeks ago. We agree that the current implementation is not very relaxed, but not wrong.

> **Describe the bug** The image component overwrites the aspect-ratio specified from css. It also generates width and height properties from the actual image size, which is incorrect.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> Add an `aspect-ratio` to your image via css class,
> 
> ```js
> <Image item={item} className="myClass" />
> ```
> 
> From css:
> 
> ```css
> .myClass {
>   aspect-ratio: 2;
> }
> ```
> 
> The result is that the accept ratio of 2 is ignored, and the image is displayed with its original aspect ratio.
> 
> **Expected behavior**
> 
> The image is displayed with the aspect ratio specified in the css.

You can customize the `aspect-ratio` by setting it in the `style` attribute on the Image component. Using the `style` attribute here is fine because we don't want to wait for the css to be parsed before the browser knows the aspect ratio, we want it to be immediately effective when the html is parsed. One thing Victor and I agreed on, though, is that we definitely need to document this specifically.

> **Additional context**
> 
> 1. Problem with generating the width and height
> 
> The Image component generates the width and the height from the image size, if not specified explicitly. This is wrong. The point of the width, height attributes is to avoid layout shift by hinting the browser in the html about the _rendered_ image size, not the _actual_ image size.
> 
> Sure, if I specify width and height then it will use these values. However putting the real image size to this attributes does not help layout shift, as the rendered image size will most certainly not be the same as the original uploaded image size.

Specifying width+height AND aspect-ratio is a bit overkill but not wrong, only one of the two is really required for proper layout shift prevention. Using the real image aspect ratio is a sane default, while leaving the option to customize it to the developer.

> Possible actions:
> 
> a. Do not generate the width and height, if not specified. Leave it to the developer. There is no way it can be predicted on SSR, what the rendered width and height will be, only the developer can know.

This is not what browsers need. Specifying width and height is enough to reduce layout shift because browsers use those sizes to calculate the aspect ratio even if the image is rendered at a different absolute size because of the site layout.
I don't want to leave this entirely to the developer, I would rather provide a sane and customizable default, so Plone can be a better product out of the box.

> b. If you think width and height are really mandatory, (imo not, as it's just a hint to avoid layout shift), then make them mandatory.

They are not mandatory for the developer, because we provide a sane default. It's the whole point of this component, to provide a smart way to avoid dealing with all optimization things when they can be inferred from the info we have from the rest api.
They are mandatory (well, those or the aspect ratio) for web vitals, but we take care of that as default, I would not remove this behavior.

> 2. aspect-ratio is overritten
> 
> In connection with problem 1, the aspect-ratio specified from css is overridden and thus the image is displayed with the wrong aspect ratio.
> 
> * If I specify width+height, it will override the aspect ratio set on the css, by using the width and height I specified
> * If I do not set width+height, it will calculate it from the image size, and again it will override the aspect ratio
> 
> In both cases it won't be the correct aspect ratio. The only way it will be correct, if I specify width and height. However this makes the aspect-ratio css attribute lose its purpose.

As said before, with the current version the proper way to customize the aspect ratio is by setting the new one in the `style` attribute. Repeating it here just to make this a complete answer.

> Possible actions:
> 
> a. do not generate the aspect-ratio, let's use css as intended, and let's leave it to the developer to use it the way they want.
> 
> b. Only generate the aspect-ratio, in case it's not already specified from css (it's possible to check this in client runtime only, no SSR) but again, kind of pointless if you also consider point 1.

I can see a point for removing the aspect ratio generation, but if we do that, the width and height automatic generation has to stay. It would need some lighthouse testing, but I am pretty sure it's fine without setting `aspect-ratio` if we have width and height. As said at the beginning, having a slightly more relaxed implementation would be fine, as long as we provide the same powerful out of the box component that can provide the same good defaults and optimizations.
