### ISSUE TITLE
Adding default template for content type with block(having schemaEnhancer) throwing error.

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#5158]
If you have a schema enhancer for a particular block and then you try to add this block in the layout options of content type will throw error.

Steps to reproduce the error.

1. Create a schemaEnhancer for a particular block
2. Go to any content type and dexterity content layout and select this block.

You will get error.

**Comment by davisagli** [comment]
@iFlameing Your report here is really vague.

Specifically we saw this when trying to add an image block to a layout in a project where the image block has a schema enhancer that tries to adjust the `align` property, which is part of the default image schema. The error is `TypeError: schema.properties.align is undefined` on this line in the schema enhancer: `schema.properties.align.default = 'wide';`

I would expect that the `align` property should be there, so we need to find out why it is not.

**Comment by tiberiuichim** [comment]
> The problem is that schema extenders are being applied to the block layout settings schema, in addition to the main block schema. 

CC @avoinea

**Comment by avoinea** [comment]
I would need a more details example of this in order to fully understand the issue and the relation with the DX Layout schema.

**Comment by davisagli** [comment]
@avoinea For example, we have a schema enhancer that adds "block width" and "background color" properties to a block. When editing the layout, the fields show up on both the Block and Settings tabs, because the schema enhancer is applied to both the block schema and the settings schema:

<img width="382" alt="Screenshot 2023-09-07 at 7 46 08 AM" src="https://github.com/plone/volto/assets/49014/83778236-cf33-45b7-a528-e50aadacee41">

<img width="387" alt="Screenshot 2023-09-07 at 7 47 29 AM" src="https://github.com/plone/volto/assets/49014/d3955b3d-feb6-4d53-bba4-929a4cb3ad9f">

Even worse, if the schema enhancer makes assumptions about the schema it is enhancing (like making a change to an existing field), then trying to use the block while editing the block layout can result in an error.

#5159 fixes this by making sure that schema enhancers are not applied to the layout settings schema.
