### ISSUE TITLE
Should be memoized

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#5175]
https://github.com/plone/volto/blame/8620a45ab9f2f441debf934264dcb4b780500993/src/components/manage/Blocks/Search/hocs/withSearch.jsx#L349

**Comment by shaikahmadnawaz** [comment]
> https://github.com/plone/volto/blame/8620a45ab9f2f441debf934264dcb4b780500993/src/components/manage/Blocks/Search/hocs/withSearch.jsx#L349

The `removeSearchQuery` function you provided can be memoized if its performance is a concern, although in this specific case, it might not offer significant benefits since the function is relatively simple. Memoization is typically useful when a function is computationally expensive and repeatedly called with the same arguments.
