### ISSUE TITLE
Switch from npm to corepack for installation?

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#5276]
See the history and discussion on https://github.com/plone/documentation/pull/1540.

I am not sure of the impact of switching from npm to corepack for installation instructions, and possibly in automation and the cookiecutter. This will need input from Volto core contributors and maintainers.

If approved, I would suggest that we update the Plone 6 documentation with the following.

````md
#### Yarn 3

Install the latest Yarn 3 version (not the Classic 1.x one).

1.  Open a terminal and type:

    ```shell
    corepack enable
    ```

2.  Verify that Yarn v3.x.x is installed and activated.

    ```shell
    yarn set version 3.x
    yarn -v
    ```
    ```console
    3.2.3
    ```


````

**Comment by dhruvgupta0503** [comment]
Hi , Can i work on this issue

**Comment by stevepiercy** [comment]
@dhruvgupta0503 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

**Comment by ichim-david** [comment]
@stevepiercy https://yarnpkg.com/getting-started/install if we look at the install docs they say to use the corepack install so I would remove the install with npm since it is discouraged by yarn install docs.
This is because we offered this way of install as an alternative for the npm install which nowadays is wrong and should be removed.
