### ISSUE TITLE
Search block facet value autopopulated with listing criteria value when you select other facet value.

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#5432]
The value of the facet is filled automatically. I haven't selected the facet value and it appears automatically when I selected the other facet value.

1. Create a search block.
2. In listing criteria select the review state and it's value. You can see the screenshot below.
3. After that in first facet select the review state once again.
4. In the second facet select the Type and save the page.
5. Go in view mode and change the Type facet to select a value a value like `Event`.

You will see the review state facet is filled automatically. Which is the bug.

https://github.com/plone/volto/assets/33936987/b45fe2c9-8d22-4ee7-8f51-80e7d214ad41

**Comment by iFlameing** [comment]
@tiberiuichim I need your suggestion regarding how to fix and what will be the best approach to solve it.

**Comment by iFlameing** [comment]
@tiberiuichim Updated the Issue with screencast which shows steps to reproduce and bug.

**Comment by tiberiuichim** [comment]
Here's the recording that @iFlameing is talking about.

https://github.com/plone/volto/assets/141568/4e785199-2575-411f-84ff-3b6955fbc126

The problem is like this:

- the search block is initialized with an empty state. It has two facet and, most important, one of the facet field is also used as part of the query criterion
- by changing the value for "the other facet", a search query is executed.
- now the search block looks at the query and populates the facets with the query values from the search
- the search query of course has values for the first facet, because it was used in the "criteria" part of the search block configuration

There's two possible fixes:

- when displaying a facet, always compare the facet value to the "default criteria". If it's the same, show the facet as "empty". This may be difficult, as there's a (maybe limited) number of possible "querystring facet values". But one difficulty, for example, a list is not a set. Although I think that with the querystring searches, we can always treat list as sets. Unless we're doing range searches.
- another fix is to derive the initial state of the search block from the Criteria query. Then the search block is displayed, from the start, with all the facet values in place.

The workaround is not to use a facet field if you have that field already in the criteria.
