### ISSUE TITLE
Wrong usage of createRef in react function component

### ISSUE THREAD

**Issue by razvanMiu** [plone/volto#5519]
In SidebarPopup component `createRef` was used in a function component which makes the reference always be `null`:
https://github.com/plone/volto/blob/16.x.x/src/components/manage/Sidebar/SidebarPopup.jsx#L12

Use `useRef` instead

**Comment by Frs2304** [comment]
Please assign me this issue @razvanMiu

**Comment by Shibbu264** [comment]
@Frs2304 @plone-foundation doen't assign issues, Read the contributing guidelines please.

**Comment by Frs2304** [comment]
Thanks for letting me know

**Comment by razvanMiu** [comment]
I already made a pr with the fix https://github.com/plone/volto/pull/5520

**Comment by TECH-Wizardz** [comment]
feat: Replace createRef with useRef in SidebarPopup component

Refactored the SidebarPopup component to use the useRef hook instead of createRef in functional components. This ensures proper reference handling in the functional component.

Changes Made:
- Replaced `const asideElement = React.createRef();` with `const asideElement = React.useRef();`
- Updated access to the ref: `if (asideElement.current && doesNodeContainClick(asideElement.current, e)) return;`
- Added dependency array to useEffect: `React.useEffect(() => { /* ... */ }, [handleClickOutside]);`

This change addresses the use of useRef in the SidebarPopup component for better compatibility and adherence to functional component best practices.

Closes: #5519

**Comment by siddoinghisjob** [comment]
Is this issue still open? I would like to work on this if it's still open.

**Comment by davisagli** [comment]
This was fixed.
