### ISSUE TITLE
Reusable components

### ISSUE THREAD

**Issue by thet** [plone/volto#59]
Is there a plan on how to separate individual functionality from the plone-react app into small reusable components?
I'd like to direct my development efforts away from mockup to something which becomes part of our Plone JavaScript strategy and I think React is currently the best fit. I'd even consider using Web Components / Polymer for the task of encapsulating components, which itself can use ReactJS.

But what is the current state regarding this topic?

**Comment by tisto** [comment]
@thet Our plan is to develop all components in plone-react itself. If people want to re-use specific components we will try to make them reusable as stand-alone components. Since plone-react uses redux and shared state in the app to make sure things work well together it is not always trivial to do so. Therefore we will only make components re-useable on request. We want to fully focus on plone-react and not put to much effort into standard Plone right now. Though, if you are interested in working on that we are more than happy to help!

**Comment by tisto** [comment]
@thet btw: I am also available for a quick chat/call regarding this topic. Just ping me on IRC/Slack.

**Comment by thet** [comment]
@tisto nice, that sounds like a pragmatic approach. I'd be happy to help out here!
I recently had a discussion about web components and Polymer and maybe this can help us here as it should play nicely with ReactJS and Redux (started a PLIP WIP here: https://github.com/plone/Products.CMFPlone/issues/2253). Thats something we should at least consider and evaluate.
I have to finish some other things before I can work on this matter. I try do get a better overview before the Alpine City Sprint and get back to you then.
@tisto are you also coming to this sprint?

**Comment by cekk** [comment]
+1 for everything

Could be great sharing widgets/components between the two worlds: plone-old and plone-react

**Comment by tisto** [comment]
@thet I would love to come but there are just too many events already in 2018. :(

Just ping me when you want to talk. @robgietema will be back from holidays next week and might be willing to join us.

Do you plan to come to Berlin in March?

**Comment by robgietema** [comment]
Closing this issue for now, when someone wants to work on this feel free.
