### ISSUE TITLE
Multiple 404 Errors Triggered for Non-Existent Pages in Volto

### ISSUE THREAD

**Issue by FarooqAlaulddin** [plone/volto#6265]
Describe the bug
When navigating to a non-existent page in a Volto site, the initial 404 error is expected. However, additional API requests, such as @breadcrumbs and @actions, are made and also return 404 errors. This results 3 404 requests for that user instead of one in nginx frontend logs. 

Is there a way to handle this without having the extra 2 404s?

To Reproduce

- I found this site that uses volto with the same issue https://forest.eea.europa.eu/knowledge/research-projects/not-found-page

Screenshots
![image](https://github.com/user-attachments/assets/6bb0a470-f5d3-41ae-8c97-ae16b8f4cd75)

Software (please complete the following information):

OS: []
Browser: []
Volto Version: [16.31]
Plone Version: [6.0.8]
Plone REST API Version: []

Additional context
extractScripts.errorPages is set to true in my volto settings.

**Comment by davisagli** [comment]
In more recent versions of Volto, the default configuration uses API expanders to fetch this additional information as part of the main content request.

You can configure Volto 16 to do the same thing by copying this configuration: https://github.com/plone/volto/blob/main/packages/volto/src/config/index.js#L220

Closing the issue since it was a support request rather than a bug.
