### ISSUE TITLE
Volto Documentation Integration with docs.plone.org

### ISSUE THREAD

**Issue by tisto** [plone/volto#67]
We should set up a documentation for plone-react. mkdocs seems to be a good fit:

http://www.mkdocs.org/

We choose Markdown over ReST because Markdown is kind of a standard in the JS world.

**Comment by tisto** [comment]
@robgietema what's your opinion here? Markdown or ReST?

**Comment by stevepiercy** [comment]
@tisto if you plan to include these docs under docs.plone.org, then I would suggest using reST. reST is an [implicit requirement](https://docs.plone.org/about/contributing/index.html#before-you-make-a-pull-request):

> * Check that you are using valid restructured text.

@svx and other docs team members may have further information.

**Comment by tisto** [comment]
@stevepiercy we are aware of that and also about the limitations of Markdown in comparison to reST. Though, plone-react is a pure ReactJS library and Markdown is pretty much standard in the JS world. Getting plone-react to the core is not on our roadmap right now.

**Comment by sneridagh** [comment]
Using mkdocs as generator, @tisto nowadays I can't see any limitation on it comparing to ReST.

https://docs.voltocms.com

We have to discuss how to integrate them in the future with Plone's ones with the documentation team.

**Comment by tisto** [comment]
@sneridagh this is something that we have to discuss with Plone 6 in mind. What do we do if Volto becomes Plone 6? Then we have to integrate our docs into docs.plone.org. @svx opinions?

**Comment by svx** [comment]
I will save the talk about differences between Sphinx and MkDocs for a different time.
Just so, much there are huge differences in the way of functionality, specs, community support, and activity, etc but this is not the point.

These days it is common that various communities use a favorite markup language.
We do the same in the 'go' world, where we use Markdown, too.

To make it short, there is NO way to include Markdown-based docs into docs.plone.org, at least not as long Plone uses reST and Sphinx.
Yes, Sphinx supports CommonMark (Markdown spec) these days, but the support is limited and the development is not really active.
For example, some Markdown features form the MkDocs Material theme, which are used in Volto, are not supported and this is only one example.

More item:

- We use various Sphinx directives which do not exist in Markdown/MkDocs
- Custom CSS selector which are bind to Sphinx directives
- Custom JS which is bind to Sphinx directives
- Custom Sphinx configuration settings which do a "search and replace" in the docs, for version numbers, etc 
- ...
- ...

The way how `toctrees` are working is different, meaning we can not include the existing file/dir setup from the Volto documentation.

And no, converting with `pandoc` will not work, `pandoc` does not speak modern Markdown and even if you use the "original" Markdown spec. you always have to fix lots of bits after you run `pandoc` :)

One other point, I was not able to find any style-guide for documentation in the Volto repository, meaing the quality in terms of wording, file structure of the docs, etc would be different and because of this we would end up with a documentaion which is party QA checked and part;y not, which decreasses the all over QA and because of this the reading exprience for the user :) 

The question is, do we have to intregarte the docs at all ?

I could go on here for hours :) but I guess this does it for now?
Feel free to ping for more! :)

**Comment by sneridagh** [comment]
Hey Sven,
As you have already checked out, the Volto docs are a very early stage and
still a work in progress, we had to start and we started with the current
iteration. You can imagine how hard is for the current Volto team to take
care of everything required to boot such an ambitious project by ourselves.
I have no doubts whatsoever about your expertise here and we are open to
find a solution for the mid-term goal that would lead to the integration
with Plone docs. I just wanted to start the conversation with my comment on
the issue!
Looking forward to discuss this soon.
Cheers,
V.

**Comment by svx** [comment]
Hey! :)
My previous comments were **not** meant as a critic!

Maybe it is time to re-think the whole Plone documentation setup as a whole?
The "stack" and tooling has changed over the last couple of years and will keep changing.
That is not "only' for the frontend part, also how installation and hosting works will change/is already changing.
Since the community is also not that huge anymore we should also take in mind that by using the "default' technologies and best practices of tools which are used within certain communities (like Markdown for ReactJS related docs) it makes it "easier" or/and more attractive for non Plone/Python people to contribute.

Yes, Sphinx and reST is superior to Markdown. You can do more with it and it has a spec (CommonMark is still not official). But does that means we have to stick with it?

For me it is not "only" about the tooling, the main focus should be to have awesome docs! If that means we switch to Markdown (only an example here), even if by doing so we would lose some cool reST features, but we would have better docs, we should think about it at least.

Like I said the "Plone stack" is changing, so we also should keep that in mind with the docs.

**Disclaimer** 
I am **NOT** saying we will change now to Markdown or something else, but now is a good time to have an open-minded discussion about it.

**Comment by stevepiercy** [comment]
I have strong doubts that anyone would undertake the behemoth task of converting the volume of Plone docs from reST to any other markup language as a volunteer. I've done small conversions using pandoc, and they always require considerable manual fixes. It would be hundreds, probably thousands, of hours of labor. Any open minded discussion without addressing this elephant in the room would be without merit.

Nonetheless I love to be proved wrong because then I learn something I did not know. Please suggest how things would be integrated or converted, who would do it, how long it would take, how much it would cost. You know, the excruciatingly boring and tedious details that result from painstaking thought, consideration, and research. Propose a proof of concept, and execute on it. Convert a section of documentation from one format to another, time how long it takes, note the bugs from conversion, evaluate what is lost and gained.

**Comment by svx** [comment]
Well :)
I never said that it will be done in 5 minutes :)
My point is we are currenlty started wirting the docs for Plone 6 from scratch anyway.
Lots of the current content will be not make it to the docs of Plone 6.

We are littely touching every file from hand, movins stuff, improviing stuff, cuitting stuff, etc.
Basically we split the 'docs team' @polyester is doing all things related to our cuttent docs and I am started workingon the docs for 6.
We have more or less a year, my "main issue' is more that I am waiting of input from the community what content will be change (like the whole frontend) stuff. :)

Like I tried to say, there is nothing decided yet, but I would love to have a tal about the furture also taken in mind new technologies which are used like ReactJS :)

**Comment by sneridagh** [comment]
https://docs.voltocms.com/ is now on https://6.dev-docs.plone.org/ WIP, but this can be closed.
