### ISSUE TITLE
Questions about changelogs

### ISSUE THREAD

**Issue by pnicolli** [plone/volto#816]
Hi :)

Noticed there's a `changelogupdater.js` file in the source that writes stuff in the changelog. I also noticed some recent releases (yay!) and was curious about what's new and I now have a couple questions:

1. What does the mentioned js file do? When submitting PRs, should I still update the `CHANGELOG.md` file manually or is there another way to update that?
2. While looking for the latest changes, I noticed there's a mismatch between `CHANGELOG.md` and the [Releases page](https://github.com/plone/volto/releases). Is that wanted and maybe temporary or is something missing, or am I missing some infos? :D

I'm willing to keep helping on the project with PRs but I want to get them right :P 
Thanks

**Comment by tisto** [comment]
@pnicolli you still need to update CHANGELOG.md manually. changelogupdater.js is part of the release process.

**Comment by sneridagh** [comment]
@pnicolli because of a project delivery we had to create a 3.x.x branch and we are releasing 3.x versions from there, that's the reason of the mismatch.

Master will become 4.0.0 soon with all the changes that were done in the Beethoven sprint, we are planning to work towards it during the next months.

**Comment by pnicolli** [comment]
Ok got it, thanks @tisto @sneridagh 👍
