### ISSUE TITLE
Using third party libraries/themes written in sass

### ISSUE THREAD

**Issue by pnicolli** [plone/volto#842]
As said in #841, we would love to start using Volto for our upcoming Plone projects and of course sometimes there are complicated things involved in business work.

We would really love to use these opportunities to start helping out with Volto development very soon (starting right away in september), but we are facing quite the blocker in order to start using it.

In Italy, for government and public administration websites, we need to use a specific ui kit with a provided css/js library. This library is based on bootstrap 4, this means it's written in sass and it has its own grid system. As a plus, it has ready-to-use react components that would speed us up by a lot.

I'm looking for discussion and suggestions here on what path we could take to create a custom theme for Volto while also using this customized bootstrap 4 version.

Problems I see:

1. Two different grid systems, typography, scaffolding and other properties
2. Mixing Semantic components and Bootstrap components
3. Adding sass compiling capabilities to the current config (maybe it's already able to, I don't know)
4. Sharing variables would be great

My first thoughts:

1. Can we just drop semantic and use my bootstrap? -> I don't think so, because that would mean styling all semantic components in the Volto core, plus styling all of Volto core (user toolbar, edit views and controlpanels, for example)
2. Can we just avoid using Pastanaga and use the default semantic theme, adding my bootstrap on top of it? -> Maybe, need to explore. Thoughts about this?
3. Should we just add the whole compiled bootstrap as css and keep styling the rest in the Volto way, while using our custom bootstrap classes for html elements? -> Maybe, but this has two issues: the first is that we would be importing the whole grid system and other base bootstrap styles that don't work well with semantic; the second would be not being able to use our bootstrap variables in our styles.
4. Should we just create a whole new Volto theme with new components etc? When I think about maintaining this, it just looks like a nightmare.
5. Should we recompile bootstrap removing all base styles and adapt the semantic base variables? Of course sharing variables would really help here. If we could share those, this would look like the best option, probably.
6. Should we maintain a less version of that custom bootstrap library and turn it into a custom theme on top of pastanaga? Thoughts? This also looks like an options.
7. Should we think about **not** using Volto at all and make our lives simpler by going the default Plone theming way for these projects? Of course this is not very appealing...

Thanks in advance for any thoughts you will share about this. I believe this will be something that several people would face in some way while approaching a Volto project in the future. Or am I wrong here?

**Comment by sneridagh** [comment]
@pnicolli Good news! I'm eager to see people start using Volto in their projects.

BTW, you just opened the Pandora's box :)

We knew the other day that the Semantic IU (the CSS framework) is a one person project and it is (poorly) maintained and almost abandoned. Luckily the React part seems in good health... 

My five cents: in a perfect world with a strong community with enough resources to afford the effort, I would separate all the core CSS from the theming one in Vainilla CSS (and most probably) using CSS in JS for that (using emotion or alike). This core will comprise all the CMS UI and common parts of Pastanaga (tiles engine included).

Then, I would use an adaptable theming story independent of the framework used. We might be even able to use something agnostic like https://theme-ui.com/ to customize the default Vainilla CSS layer.

In a more approachable way, Semantic UI has a very valuable thing: the CSS is highly specific. So all the declarations are `.ui ... ` so in theory, it might not clash with other CSS framework... (something that we will have to try), only with the overhead of having two frameworks in the same app. I can imagine that one could be able to remove all the CSS modules from Semantic UI config and leave it to the minimum only to be used for the CMS UI and tiles engine.
https://github.com/plone/volto/blob/master/theme/theme.config

However, we never made it configurable and it's hardcoded in Volto itself, although it might be easy to extract it and be used by the project.

I would suggest to schedule a meeting, and talk about all this. What do you think?

/cc @robgietema @cekk @tisto

**Comment by cekk** [comment]
A big 👍 from me. I totally agree your thoughts.

As @pnicolli said, we discussed about it yesterday and considering that we have 4 potential projects that could start with Volto and that ui kit, we may put some effort for this thing in next months.

We could schedule a meeting as you proposed of course. My contribution will be below zero because i don't know these stylish things, but i'm interested in topic.
@pnicolli and @nzambello could fill the gap 😉

**Comment by attackemartin** [comment]
upvote!

**Comment by TBCcrash2064** [comment]
Uh that would be nice! Volto is a big chance for Plone and I think it would make sense to use a well maintained framework. Switching to Bootstrap and SASS would be great. Maybe we could help if this will be an option...

**Comment by TBCcrash2064** [comment]
And... there is also a Bootstrap React ;) https://react-bootstrap.github.io

**Comment by pnicolli** [comment]
@TBCcrash2064 I think that just by changing the framework that is behind the theme we would not solve the issue, it would just turn it the other way around for LESS users, for example. Probably going for a more detachable or interchangeable theme would be better.

**Comment by djay** [comment]
@sneridagh.   I think the better approach is two separate themes rather than clever seperation of css between editing and view modes. Let's say volto-view and volto-edit themes In the default case you build your site on volto-edit and volto-view with a shared css customisation file. Then you get the nice wysiwyg volto editing experience you get now. 
 But also supported would be using volto-edit and a completely different custom-view theme that might have little shared css, js and may not even use react. It would be up to the themer how much work they want to put into customising their volto-edit to make it similar to custom-view so editors get a more wysiwyg editing experience. The important thing is whatever goes into volto-view is minimal and easy to replace with alternatives. 

I take your point it makes volto much much harder. It also compromises the UX in that you no longer get a 100% wysiwyg, but this is a needed compromise for some projects.

@pnicolli +10 the seperation of editing theme/js dep from the public theme vs editing UI was a big win for us too with plone 5. Your point that some clients have mandated templates with specific js/css is important. 
We've also done conversion projects from other CMSes where the client had to keep the same theme due to costs or compliance or politics. We've even used mosaic on our edit view using barceloneta and deco grids and mapped this on the public theme to bootstrap grids. It works pretty well.

**Comment by pnicolli** [comment]
@djay @attackemartin @TBCcrash2064 First draft of implementation in #970, feel free to test that even if still very experimental.
