### ISSUE TITLE
Add ability to merge configurations coming from addons

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#871]
Given an addon, pulled from mrs.developer we need the ability to be able to merge the default Volto configuration object with an addon one, then merge with the local project one.

**Comment by tiberiuichim** [comment]
We've taken this approach with out addons (visible in this file: https://github.com/eea/forests-frontend/blob/master/src/config.js ):

- in the config.js file, we import configuration methods from other addon packages
- we import all exports of Volto's config as: `` import * as voltoConfig from '@plone/volto/config';``
- we call these configuration methods, passing the config object and allowing packages to mutate the config, with:

```
const config = [
    addonConfigA,
    addonConfigB,
].reduce((acc, apply) => apply(acc), voltoConfig);
```

- and then export everything is needed from this reduced config object.

We took this approach and mutate the config directly in order to allow more freedom in how addons mutate the config, what we include from the addons (make some addon features optional, for example) and to reduce the need of large code blocks with many spreads.

**Comment by tiberiuichim** [comment]
One thing that was tricky and required some tooling work was allowing addon packages to have their own requirements, which meant we needed to ``npm install`` the addon, which then copies the addon to node_modules and needs to be that location. This could also be achieved, probably, with ``npm link``.

**Comment by sneridagh** [comment]
Dupe and solved already :)
