### ISSUE TITLE
Pastanaga Editor: Discuss architecture and how to approach it

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#90]
Leave a boilerplate in place would be great also.

- How we are going to choose between the available editor experiences? (Classic, Mosaic, Pastanaga/Pastanaga Lite (DVV))
- How all the editor experiences will coexist?

**Comment by singhrohan62** [comment]
Hey @sneridagh I am interested in contributing in the implementation of Pastanaga editor. However, I am unable to find enough sources to get to know more about its architecture, so if possible, kindly provide me the instructions for exploring more about it so that I can contribute in its implementation. Thanks!

**Comment by robgietema** [comment]
Basic implementation done, more work will follow.
